---

all:
  hosts:
  children:

# Mise en place hôtes

    VM:
      hosts:

        web:
          ansible_host: 192.168.20.50
        web_2:
          ansible_host: 192.168.20.80
        bdd_wiki:
          ansible_host: 192.168.20.5

    bdd_wiki:
      hosts:
        BDD:
          ansible_host: 192.168.20.5

    web:
      hosts:
        WEB1:
          ansible_host: 192.168.20.50
        web_2:
          ansible_host: 192.168.20.80


# Tentative echoué
    LoadBalancer:
      hosts:
        load_Bal_1:
          ansible_host: 192.168.20.50
